# Generated by Django 5.0.6 on 2024-06-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_remove_cartitem_product_name_cart_pricetotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='priceTotal',
        ),
    ]
